name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set execute permission for Maven Wrapper
        run: chmod +x ./mvnw

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: ./mvnw install

      - name: Run tests
        run: ./mvnw test

      - name: Generate build artifacts
        run: ./mvnw package

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set execute permission for AWS CLI
        run: chmod +x /usr/local/bin/aws

      - name: Deploy to AWS Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          zip -r app.zip .
          aws elasticbeanstalk create-application-version \
            --application-name my-app \
            --version-label v1 \
            --source-bundle S3Bucket=my-bucket,S3Key=app.zip
          aws elasticbeanstalk update-environment \
            --application-name my-app \
            --environment-name my-env \
            --version-label v1
